version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: grunt-contrib-uglify
    versions:
    - 5.0.0
  - dependency-name: grunt-contrib-less
    versions:
    - 2.0.0
  - dependency-name: grunt-contrib-cssmin
    versions:
    - 3.0.0
